// <auto-generated />
namespace IT_Inventory.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _52 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_52));
        
        string IMigrationMetadata.Id
        {
            get { return "201706091034342_52"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
